[[redirects]]
  from = "/sets/:setId"
  to = "/deeplink.html?setId=:setId"
  status = 301

[[redirects]]
  from = "/song/:songId"
  to = "/deeplink.html?songId=:songId"
  status = 301

[[redirects]]
  from = "/lyrics/:songNumberId"
  to = "/deeplink.html?songNumberId=:songNumberId"
  status = 301
