[[redirects]]
  from = "/sets/:setId"
  to = "worshipbuddy://sets?:setId"
  status = 301
  
[[redirects]]
  from = "/song/:songId"
  to = "worshipbuddy://song?:songId"
  status = 301

[[redirects]]
  from = "/lyrics/:songNumberId"
  to = "worshipbuddy://lyrics?:songNumberId"
  status = 301
