[[redirects]]
  from   = "/share/:region/song/:songId"
  to     = "/deeplink.html?region=:region&songId=:songId"
  status = 302

[[redirects]]
  from   = "/share/:region/lyrics/:songNumberId"
  to     = "/deeplink.html?region=:region&songNumberId=:songNumberId"
  status = 302

[[redirects]]
  from = "/sets/:setId"
  to = "/deeplink.html?setId=:setId"
  status = 301

[[redirects]]
  from = "/song/:songId"
  to = "/deeplink.html?songId=:songId"
  status = 301

[[redirects]]
  from = "/lyrics/:songNumberId"
  to = "/deeplink.html?songNumberId=:songNumberId"
  status = 301
